#: kivy 1.10.0
#: import CardTransition kivy.uix.screenmanager.CardTransition
#: import NoTransition kivy.uix.screenmanager.NoTransition
#: import FadeTransition kivy.uix.screenmanager.FadeTransition
#: import RiseInTransition kivy.uix.screenmanager.RiseInTransition

ScreenManager:
    id: screen_manager
    transition: NoTransition()
    # MenuScreen:
        # id: menu_screen
        # name: 'menu'
        # manager: 'screen_manager'
    # SettingsScreen:
    #     id: settings_screen
    #     name: 'settings'
    #     manager: 'screen_manager'
    ScreenOne:
        id: scr_one
        name: 'screen_one'
        manager: 'screen_manager'
    ScreenTwo:
        id: scr_two
        name: 'screen_two'
        manager: 'screen_manager'
    ScreenThree:
        id: scr_three
        name: 'screen_three'
        manager: 'screen_manager'
    ScreenFour:
        id: scr_four
        name: 'screen_four'
        manager: 'screen_manager'

<MenuScreen>:
    BoxLayout:
        Button:
            text: 'Goto settings'
            # on_press: app.root.current = 'settings'
            on_press: app.root.current = 'settings'
        Button:
            text: 'Quit'

<SettingsScreen>:
    BoxLayout:
        Button:
            text: 'My settings button'
        Button:
            text: 'Back to menu'
            on_press: app.root.current = 'menu'


<ScreenOne>:
	BoxLayout:
		Button:
			text: "Go to Screen 2"
			on_press:   
                app.root.current='screen_two'
                app.root.transition=FadeTransition()
            	app.root.transition.direction = 'left'
				app.root.transition.duration = 1

<ScreenTwo>:
	BoxLayout:
		Button:
			text: "Go to Screen 3"
			on_press: 
                app.root.current='screen_three'
                app.root.transition: NoTransition()
                app.root.transition.direction = 'up'
				app.root.transition.duration = 0.5



<ScreenThree>:
	BoxLayout:
		Button:
			text: "Go to Screen 4"
			background_color : 1, 0, 1, 1
			on_press:
                app.root.transition: RiseInTransition()
                app.root.transition.direction = 'right'
				app.root.transition.duration = 1
				app.root.current = 'screen_four'

<ScreenFour>:
	BoxLayout:
		Button:
			text: "Go to Screen 1"
			background_color : 0, 1, 1, 1
			on_press:
                app.root.transition.direction = 'down'
				app.root.transition.duration = 0.5
                app.root.current = 'screen_one'

# <ScreenFive>:
# 	BoxLayout:
# 		Button:
# 			text: "Go to Screen 1"
# 			background_color : 1, 0, 0, 1
# 			on_press:
				# root.manager.transition.direction = 'right'
				# root.manager.current = 'screen_one'