#: kivy 1.10.0

ScreenManager:
    id: screen_manager
    MenuScreen:
        id: menu_screen
        name: 'menu'
        manager: 'screen_manager'
    SettingsScreen:
        id: settings_screen
        name: 'settings'
        manager: 'screen_manager'

<MenuScreen>:
    BoxLayout:
        Button:
            text: 'Goto settings'
            on_press: app.root.current = 'settings'
        Button:
            text: 'Quit'

<SettingsScreen>:
    BoxLayout:
        Button:
            text: 'My settings button'
        Button:
            text: 'Back to menu'
            on_press: app.root.current = 'menu'